version: "3.9"

services:
  postgres:
    image: postgres:16.11
    container_name: notesportal-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notesportal-network

  notesapi:
    image: ${DOCKER_USERNAME}/notesportal-api:${IMAGE_TAG:-latest}
    container_name: notesportal-api
    restart: always
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultDbConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - notesportal-network

  notesapp:
    image: ${DOCKER_USERNAME}/notesportal-app:${IMAGE_TAG:-latest}
    container_name: notesportal-app
    restart: always
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultDbConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NOTESAPP_ENV_CHECK=${NOTESAPP_ENV_CHECK}
    depends_on:
      postgres:
        condition: service_healthy
      notesapi:
        condition: service_started
    networks:
      - notesportal-network
    volumes:
      - /data/notesapp/images:/app/wwwroot/images

networks:
  notesportal-network:
    driver: bridge

